### ISSUE TITLE
Additional modules required beyond pip3 install -i https://test.pypi.org/simple/ bd-export-spdx2.2

### ISSUE THREAD

**Issue by acowan61** [matthewb66/bd_export_spdx2.2#4]
bd-export-spdx2.2 requires the aiohttp and lxml modules and they are not installed with bd-export-spdx2.2 using test.pypi.org/simple.

However, when I loaded those modules and attempted to run bd-export-spdx2.2, I got:

2021-10-31 16:17:50,334:INFO:Using a session with a 15 second timeout and up to 3 retries per request
BLACK DUCK SPDX EXPORT SCRIPT VERSION 0.21

2021-10-31 16:17:50,336:WARNING:ssl verification disabled, connection insecure. do NOT use verify=False in production!
2021-10-31 16:17:50,416:INFO:success: auth granted until 2021-10-31 18:17:50.413098-04:00
Working on project '<project name>' version '<project version>'

Getting component list ... (67)
Traceback (most recent call last):
  File "/usr/local/bin/bd_export_spdx", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/export_spdx/main.py", line 133, in run
    process.process_project(project, version, toppackage, hierarchical_bom, bearer_token)
  File "/usr/local/lib/python3.6/site-packages/export_spdx/process.py", line 239, in process_project
    comp_data_dict = asyncio.run(async_main(bom_compsdict, bearer_token, version))
AttributeError: module 'asyncio' has no attribute 'run'

FYI.

**Comment by acowan61** [comment]
OK.   Apparently, there is a minimum requirement for Python here.

With Pete Jalajas (Synopsys) helped me with this.   The following should get people up and running if there is an issue:

In this example, Andy made a /mnt/hub/spdx and /mnt/hub/spdx/pipenv directories.  Scripts to run SPDX 2.2 were located in /mnt/hub/spdx and the pipfile was created and located in /mnt/hub/spdx/pipenv.   This latter item could be anywhere.  It did not need to be a subdirectory.  It could be in ~/piptahdah or whatever.

Server (Red Hat):
sudo yum install rh-python38.x86_64 rh-python38-python-devel.x86_64 rh-python38-python-pip.noarch

First Time for user as user:
cd /mnt/hub/spdx/pipenv
pip install --user pipenv
~/.local/bin/pipenv --python /bin/python3.8 shell
pip3 install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple bd-export-spdx2.2
<Done. Yeah!>
cd /mnt/hub/scripts/spdx and Run scripts
Exit

to go back in:
cd /mnt/hub/scripts/spdx/pipenv   (Where your Pipfile is located)
~/.local/bin/pipenv shell
